Logo line break
sunpy/sunpy-logo pull request #8
Opened 2017-05-17 10:01 UTC by Cadair

2017-05-18 11:11 UTC, dpshelio commented on convert.py
> +subprocess.call(["./webicon.sh", "sunpy_icon.svg"])
wouldn't be better instead to use: 
```python
subprocess.call(["bash", "webicon.sh", "sunpy_icon.svg"])
```
so it runs even if the permissions are not set properly?

2017-05-18 11:48 UTC, Cadair commented on convert.py
> +subprocess.call(["./webicon.sh", "sunpy_icon.svg"])
It will run anyway right? I have no idea how subprocess handles such things?

2017-06-08 18:34 UTC, ehsteve requested changes
I would recommend that this older style be added to the list of styles and not replace the new one.

2017-06-11 19:16 UTC, dpshelio commented on convert.py
> +subprocess.call(["./webicon.sh", "sunpy_icon.svg"])
No, it doesn't. I've just run a test and I've got:
```python
PermissionError: [Errno 13] Permission denied
```

2017-06-11 19:18 UTC, dpshelio commented
I don't understand @ehsteve comment about the sytle...

2017-06-12 20:14 UTC, ehsteve commented
@dpshelio I'm suggesting we just keep both styles with and without the linebreak.

2017-12-14 10:45 UTC, closed without merging